server:
  port: 8080
  tomcat:
    accept-count: 10
    max-connections: 10
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: pruebas
  datasource:
    url: jdbc:postgresql://ep-lively-snowflake-a4ka8wiz-pooler.us-east-1.aws.neon.tech/inventarioAF?sslmode=require
    username: inventarioAF_owner
    password: npg_V0iseS8AKGHl
    driver-class-name: org.postgresql.Driver
    
    hikari:
      connection-timeout: 500 
      max-lifetime: 300000 
      idle-timeout: 60000 
      maximum-pool-size: 10 
  sql:
    init:
      continue-on-error: false
  jackson:
    default-property-inclusion: NON_NULL

  